In [1]:
import pandas as pd
import numpy as np

# Dot Product Example (nut butter sales) 

In [2]:
np.random.seed(0)

In [3]:
# Number of jars sold
sales_amount = np.random.randint(20, size=(5, 3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [4]:
# Create a weekly_sales Dataframe

In [6]:
weekly_sales = pd.DataFrame(sales_amount, index=['Mon', 'Tue', 'Wed', 'Thurs', 'Fri'],
                           columns=['Almond butter', 'Peanut butter', 'Cashew butter'])

weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [7]:
# Create price array

In [8]:
prices = np.array([10, 8, 12])

In [9]:
prices

array([10,  8, 12])

In [10]:
# Create butter_prices DataFrame

In [12]:
butter_prices = pd.DataFrame(prices, index=['Price'],
                              columns=['Almond butter', 'Peanut butter', 'Cashew butter'])

ValueError: Shape of passed values is (3, 1), indices imply (1, 3)

In [13]:
butter_prices = pd.DataFrame(prices.reshape(1, 3), index=['Price'],
                              columns=['Almond butter', 'Peanut butter', 'Cashew butter'])

In [14]:
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [15]:
prices

array([10,  8, 12])

In [16]:
prices.shape

(3,)

In [17]:
sales_amount.shape

(5, 3)

In [18]:
total_sales = prices.dot(sales_amount)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [19]:
# Shape not aligned, so we Transpose

In [20]:
total_sales = prices.dot(sales_amount.T)

In [21]:
total_sales

array([240, 138, 458, 232, 142])

In [22]:
total_sales.shape

(5,)

In [23]:
# Create daily_sales

In [24]:
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [25]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [26]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [27]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [28]:
daily_sales

Mon  Tue  Wed  Thurs  Fri
Price  240  138  458    232  142

In [29]:
# This doesnt work, its the wrong shape

weekly_sales['Total (£)'] = daily_sales
weekly_sales

ValueError: Wrong number of items passed 5, placement implies 1

In [30]:
weekly_sales['Total (£)'] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total (£)
Mon               12             15              0        240
Tue                3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

# New example (car sales)

In [32]:
car_sales = np.random.randint(20, size=(7, 5))
car_sales

array([[10,  3, 11, 18,  2],
       [ 0,  0,  4,  5,  6],
       [ 8, 17, 15,  4,  9],
       [10,  1,  1,  7,  9],
       [ 3,  6, 11, 14, 18],
       [ 0, 14,  3, 12, 10],
       [11,  4,  6,  4, 15]])

In [33]:
car_dataframe = pd.DataFrame(car_sales, index=['Mon', 'Tue', 'Wed', 'Thurs', 'Fri', 'Sat', 'Sun'], 
                            columns=['Tesla', 'Audi', 'BMW', 'Meastro', 'Micra'])
car_dataframe

Tesla  Audi  BMW  Meastro  Micra
Mon       10     3   11       18      2
Tue        0     0    4        5      6
Wed        8    17   15        4      9
Thurs     10     1    1        7      9
Fri        3     6   11       14     18
Sat        0    14    3       12     10
Sun       11     4    6        4     15

In [34]:
# Create a price_array

In [35]:
car_price_array = np.array([12000, 10000, 10000, 500, 200 ])


In [36]:
car_price_array

array([12000, 10000, 10000,   500,   200])

In [37]:
car_price_array.shape, car_sales.shape

((5,), (7, 5))

In [38]:
car_prices = pd.DataFrame(car_price_array.T, index=['Prices'], 
                          columns=['Tesla', 'Audi', 'BMW', 'Meastro', 'Micra'])

ValueError: Shape of passed values is (5, 1), indices imply (1, 5)

In [39]:
car_prices = pd.DataFrame(car_price_array, index=['Prices'], 
                          columns=['Tesla', 'Audi', 'BMW', 'Meastro', 'Micra'])

ValueError: Shape of passed values is (5, 1), indices imply (1, 5)

In [40]:
car_prices = pd.DataFrame(car_price_array.reshape(1, 5), index=['Prices'], 
                          columns=['Tesla', 'Audi', 'BMW', 'Meastro', 'Micra'])

In [41]:
car_prices

Tesla   Audi    BMW  Meastro  Micra
Prices  12000  10000  10000      500    200

In [43]:
car_sales.shape

(7, 5)

In [45]:
car_price_array.shape

(5,)

In [47]:
total_car_sales = car_price_array.dot(car_sales.T)

In [48]:
total_car_sales

array([269400,  43700, 419800, 145300, 216600, 178000, 237000])

In [50]:
car_dataframe['Total (£)'] = total_car_sales.T

In [51]:
car_dataframe

Tesla  Audi  BMW  Meastro  Micra  Total (£)
Mon       10     3   11       18      2     269400
Tue        0     0    4        5      6      43700
Wed        8    17   15        4      9     419800
Thurs     10     1    1        7      9     145300
Fri        3     6   11       14     18     216600
Sat        0    14    3       12     10     178000
Sun       11     4    6        4     15     237000