# Comparison Operators

In [1]:
import pandas as pd
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])
ones = np.ones(3)
a2 = np.array([[1., 2., 3.3], [4., 5., 6.5]] )
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
massive_array = np.random.random(100000)
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [3]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [4]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [5]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [6]:
type(bool_array)

numpy.ndarray

In [7]:
bool_array.dtype

dtype('bool')

In [8]:
a1 < 5

array([ True,  True,  True])

In [9]:
a1 == a1

array([ True,  True,  True])

In [10]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])