# Creating Arrays

In [1]:
import numpy as np
import pandas as pd


sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

# shift + tab to get docstring



In [ ]:
ones = np.ones((2,3))

In [3]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
type(ones)

numpy.ndarray

In [5]:
zeros = np.zeros((2, 3))

In [6]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
range_array = np.arange(0, 10, 2)

In [8]:
range_array

array([0, 2, 4, 6, 8])

In [9]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[8, 2, 0, 4, 1],
       [0, 8, 5, 4, 1],
       [1, 5, 5, 1, 9]])

In [10]:
random_array.size

15

In [11]:
random_array.shape

(3, 5)

In [19]:
rand_1 = np.random.random((5, 3,))

In [21]:
rand_1

array([[0.95688186, 0.01553964, 0.02714551],
       [0.5991802 , 0.16780339, 0.62072683],
       [0.90801412, 0.06273655, 0.0397154 ],
       [0.30185117, 0.35113155, 0.529015  ],
       [0.86715083, 0.14708459, 0.06633305]])

In [22]:
rand_1.ndim

2

In [23]:
rand_2 = np.random.random((5, 3, 2))

In [24]:
rand_2

array([[[0.34759729, 0.38011707],
        [0.12515656, 0.90410319],
        [0.66009497, 0.30528849]],

       [[0.51692631, 0.35681911],
        [0.15425317, 0.70773905],
        [0.05808371, 0.4796487 ]],

       [[0.06807538, 0.39811122],
        [0.58172231, 0.39452561],
        [0.14546315, 0.94815475]],

       [[0.9177081 , 0.42242368],
        [0.94238639, 0.31620113],
        [0.62512879, 0.32936   ]],

       [[0.12362799, 0.70826131],
        [0.88352373, 0.62211725],
        [0.46830491, 0.45068035]]])

In [25]:
rand_2.ndim

3

In [27]:
random_array_3 = np.random.rand(5, 3)

In [28]:
random_array_3

array([[0.14682597, 0.15336884, 0.5994976 ],
       [0.9340773 , 0.37718936, 0.56196102],
       [0.89635651, 0.30727299, 0.3385623 ],
       [0.85739497, 0.66887243, 0.90036512],
       [0.9518299 , 0.29961574, 0.9220469 ]])