In [1]:
import numpy as np
import pandas as pd

# Pseudo-random numbers

In [2]:
np.random.seed()

In [4]:
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[6, 4, 1],
       [2, 4, 9],
       [3, 4, 6],
       [0, 9, 2],
       [0, 5, 0]])

In [6]:
np.random.seed(seed=42)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

# Viewing Arrays and Matrices

In [7]:
np.unique(random_array_4)

array([2, 3, 4, 5, 6, 7, 9])

In [8]:
a1 = np.array([1,2,3])

In [9]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [10]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [11]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [12]:
a1[0]

1

In [13]:
a1[2]

3

In [14]:
a2[0]

array([1. , 2. , 3.3])

In [15]:
a2[0][1]

2.0

In [16]:
a2[1][2]

6.5

In [17]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [18]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[4, 1, 7, 5, 1],
         [4, 0, 9, 5, 8],
         [0, 9, 2, 6, 3],
         [8, 2, 4, 2, 6]],

        [[4, 8, 6, 1, 3],
         [8, 1, 9, 8, 9],
         [4, 1, 3, 6, 7],
         [2, 0, 3, 1, 7]],

        [[3, 1, 5, 5, 9],
         [3, 5, 1, 9, 1],
         [9, 3, 7, 6, 8],
         [7, 4, 1, 4, 7]]],


       [[[9, 8, 8, 0, 8],
         [6, 8, 7, 0, 7],
         [7, 2, 0, 7, 2],
         [2, 0, 4, 9, 6]],

        [[9, 8, 6, 8, 7],
         [1, 0, 6, 6, 7],
         [4, 2, 7, 5, 2],
         [0, 2, 4, 2, 0]],

        [[4, 9, 6, 6, 8],
         [9, 9, 2, 6, 0],
         [3, 3, 4, 6, 6],
         [3, 6, 2, 5, 1]]]])

In [19]:
# trying to get 9,9,2 (second block, second row)

In [20]:
a4[1][2][1][:3]

array([9, 9, 2])

In [21]:
# get the first 4 numbers of the inner most arrays

In [23]:
a4[:, :, :, :4]

array([[[[4, 1, 7, 5],
         [4, 0, 9, 5],
         [0, 9, 2, 6],
         [8, 2, 4, 2]],

        [[4, 8, 6, 1],
         [8, 1, 9, 8],
         [4, 1, 3, 6],
         [2, 0, 3, 1]],

        [[3, 1, 5, 5],
         [3, 5, 1, 9],
         [9, 3, 7, 6],
         [7, 4, 1, 4]]],


       [[[9, 8, 8, 0],
         [6, 8, 7, 0],
         [7, 2, 0, 7],
         [2, 0, 4, 9]],

        [[9, 8, 6, 8],
         [1, 0, 6, 6],
         [4, 2, 7, 5],
         [0, 2, 4, 2]],

        [[4, 9, 6, 6],
         [9, 9, 2, 6],
         [3, 3, 4, 6],
         [3, 6, 2, 5]]]])

In [24]:
a4[:, :, :, :3]

array([[[[4, 1, 7],
         [4, 0, 9],
         [0, 9, 2],
         [8, 2, 4]],

        [[4, 8, 6],
         [8, 1, 9],
         [4, 1, 3],
         [2, 0, 3]],

        [[3, 1, 5],
         [3, 5, 1],
         [9, 3, 7],
         [7, 4, 1]]],


       [[[9, 8, 8],
         [6, 8, 7],
         [7, 2, 0],
         [2, 0, 4]],

        [[9, 8, 6],
         [1, 0, 6],
         [4, 2, 7],
         [0, 2, 4]],

        [[4, 9, 6],
         [9, 9, 2],
         [3, 3, 4],
         [3, 6, 2]]]])

In [25]:
a4[:, :, :, :2]

array([[[[4, 1],
         [4, 0],
         [0, 9],
         [8, 2]],

        [[4, 8],
         [8, 1],
         [4, 1],
         [2, 0]],

        [[3, 1],
         [3, 5],
         [9, 3],
         [7, 4]]],


       [[[9, 8],
         [6, 8],
         [7, 2],
         [2, 0]],

        [[9, 8],
         [1, 0],
         [4, 2],
         [0, 2]],

        [[4, 9],
         [9, 9],
         [3, 3],
         [3, 6]]]])

In [26]:
a4[:, :, :, :1]

array([[[[4],
         [4],
         [0],
         [8]],

        [[4],
         [8],
         [4],
         [2]],

        [[3],
         [3],
         [9],
         [7]]],


       [[[9],
         [6],
         [7],
         [2]],

        [[9],
         [1],
         [4],
         [0]],

        [[4],
         [9],
         [3],
         [3]]]])