In [1]:
import numpy as np

# Datatypes and Attributes 

In [2]:
# NumPy's main datatype is ndarray

In [3]:
a1 = np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [10]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [11]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [12]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
type(a3)

numpy.ndarray

In [13]:
a1.shape

(3,)

In [14]:
a2.shape

(2, 3)

In [15]:
a3.shape

(2, 3, 3)

In [16]:
a1.ndim

1

In [17]:
a2.ndim

2

In [18]:
a3.ndim

3

In [19]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [22]:
a1.dtype

dtype('int32')

In [23]:
a2.dtype

dtype('float64')

In [24]:
a3.dtype

dtype('int32')

In [25]:
a1.size, a2.size, a3.size

(3, 6, 18)

# Create a Dataframe from NumPy array

In [26]:
import pandas as pd

In [27]:
df = pd.DataFrame(a2)

In [28]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5